import Head from 'next/head';
import Axios from 'axios';
import Link from 'next/link';
import { Fragment, useEffect, useState } from 'react';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

import { Post } from '../types';

dayjs.extend(relativeTime);

export default function Home() {
  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {
    Axios.get('/posts')
      .then((res) => setPosts(res.data))
      .catch((err) => console.log(err));
  }, []);

  return (
    <div className="pt-12">
      <Head>
        <title>Groupomania</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container flex flex-col pt-4 ">
        {/* Posts feed */}
        <div className="w-160"></div>
        {posts.map((post) => (
          <div key={post.identifier} className="flex mb-4 bg-white rounded">
            {/* Vote Section */}
            <div className="w-10 text-center bg-gray-200 rounded-l">
              <p>V</p>
            </div>
            {/* Post Data Section */}
            <div className="w-full p-2">
              <div className="flex items-center">
                <Link href={`/r/${post.subName}`}>
                  <Fragment>
                    <img
                      src="https://www.gravatar.com/avatar/00000000000000000000000000000000?d=wavatar&f=y"
                      className="w-6 h-6 mr-1 rounded-full cursor-pointer"
                    />
                    <a className="text-xs cursor-pointer font-bold-hover:underline">
                      /r/{post.subName}{' '}
                    </a>
                  </Fragment>
                </Link>
                <p className="text-xs text-gray-500">
                  <span className="mx-1">·</span>
                  Posted by
                  <Link href={`/u/${post.username}`}>
                    <a className="mx-1 hover:underline">/u/{post.username}</a>
                  </Link>
                  <Link href={post.url}>
                    <a className="mx-1 hover:underline">
                      {dayjs(post.createdAt).fromNow()}
                    </a>
                  </Link>
                </p>
              </div>
              //TODO ADD TEXT BODY 28:18
            </div>
          </div>
        ))}

        {/* Sidebar */}
        <h1>Recent Posts</h1>
      </div>
    </div>
  );
}
